# Site
repository: boevoibaran/boevoibaran.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexandr Kudrin
title: Game Developer
email: alexandr.kudrin.a@gmail.com


# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  boevoibaran
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: boevoibaranboris
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/boevoibaranboris

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Alexandr =)

  My tech expertise lies in <mark>Unity</mark> and <mark>C#</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Helio
        link: heliogames.com
        # link_text: boringcompany.com
        sub_title: Unity and server developer
        caption: June 2021 - Present
        quote: >
          Development as a backend developer.
        description: | # this will include new lines to allow paragraphs
            Support and development of game mechanics and game server. Implementation of monitoring systems for microservices and ensuring the smooth operation of servers.
      - layout: left
        title: Nival
        link: nival.com
        sub_title: Unity developer
        caption: January 2019 - June 2021
        quote: >
          Starting a career in game development.
        description: | 
            Made my way from junior to middle C# dev. Supported several existing titles and contributed to couple prototypes that were not released.

  - title: Projects
    layout: text
    content: |
      [Some of my projects you could find over here](portfolio)

  - title: Skills
    layout: text
    content: | 
      <mark>Unity</mark> <mark>C#</mark> <mark>.Net Core</mark> <mark>Python</mark> <mark>Golang</mark> <mark>Docker</mark> <mark>MongoDB</mark> <mark>Postgres</mark> <mark>Redis</mark> <mark>Git</mark> <mark>Postman</mark> <mark>Jira</mark> <mark>Estimating</mark> <mark>Legacy digging</mark>

  - title: Portfolio
    layout: list
    content:
      - layout: top-middle
        title: "Mutiny: Pirate Survival RPG"
        additional_links:
          - title:  YouTube
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=4wbXPQjcY1w
          - title:  Google Play
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.heliogames.pirates
          - title:  App Store
            icon: fab fa-app-store
            url: https://apps.apple.com/ru/app/mutiny-pirate-survival-rpg/id1490838880
        description: |
          
          <img src="images/portfolio/mutiny_poster1.png" width="33%" align="right"/>
          <img src="images/portfolio/mutiny_poster2.png" width="33%" align="right"/>
          <img src="images/portfolio/mutiny_poster3.png" width="33%" align="right"/>

          #### Project
          - Survival RPG    
          - Pirate crew management    
          - Async PvP    
          
          #### My part
          - Server architecture design
          - Development of microservices for existing business tasks
          - Support and development of meta game mechanics
          - Development of the anti-cheat system

          #### Tech & skills
          <mark>Tech planning</mark> <mark>Roadmap composing</mark> <mark>Perfomance monitoring</mark>

      - layout: top-middle
        title: "Prime World: Defenders 2"
        additional_links:
        - title:  Google Play
          icon: fab fa-google-play
          url: https://play.google.com/store/apps/details?id=com.nival.pwdefenders2
        - title:  App Store
          icon: fab fa-app-store
          url: https://apps.apple.com/us/app/defenders-2-tower-defense-ccg/id939529493
        description: |
          <img src="images/portfolio/defenders2_gameplay1.png" width="33%" align="right"/>
          <img src="images/portfolio/defenders2_gameplay2.png" width="33%" align="right"/>
          <img src="images/portfolio/defenders2_gameplay3.png" width="33%" align="right"/>

          #### Project
          - Mobile + Standalone game
          - Tower defense
          - With CCG elements
          - Still in operation
          - Async PvP   
          
          #### My part
          - Support and development of the game client and server
          - Support of existing SDKs
          - Development of tools for QA and game designers
          - Refactoring and bugfix

          #### Tech & skills  
          <mark>Steam</mark> <mark>ECS</mark> <mark>Server progress saves</mark> <mark>Client server interaction</mark> <mark>NGUI</mark> <mark>Appsflyer</mark> <mark>Firebase</mark>    

      - layout: top-middle
        title: PL & FK
        description: |
          <img src="images/portfolio/firekeeper_logo.png" width="33%" align="right"/>

          #### Project
          - Standalone and mobile adventure-survival-strategy-RPG
          - Async PvP   
          
          #### My part
          - C# programming
          - Interface layout
          - Development of unity editor extensions

          #### Tech & skills  
          <mark>Unity</mark> <mark>UI</mark> <mark>ECS</mark> <mark>Telepathy</mark> <mark>Synchronous multiplayer</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
